### ISSUE TITLE
Loop videos in playlist without looping the playlist.

### ISSUE THREAD

**Issue by hudakdidit** [ronik-design/react-drive-in#16]
Hi awesome component! Apologies if I've overlooked this is the documentation, but is it possible via the component api for the videos in a playlist to loop without looping the playlist itself? Thanks.

**Comment by mshick** [comment]
It isn't possible right now, but I can add it in. If you don't mind my asking, what's the application you had in mind?

**Comment by hudakdidit** [comment]
@mshick Thanks for the quick reply! I'm building a react app that has steps, and I'd like to trigger the next video loop in the playlist when the step advances. Does that make sense? IMO it might make sense for there to be an option to loop the videos, as well as a separate option to loop the playlist.

**Comment by mshick** [comment]
Interesting. I’ll definitely get the feature working soon.

**Comment by mshick** [comment]
@hudakdidit I added that feature today. Please test it out. Sorry it took me so long!

**Comment by mshick** [comment]
@hudakdidit ping. Will close this issue in a couple days if I don't hear back.
