### ISSUE TITLE
Allow a configurable parent (don't hijack body) for multiple els per page.

### ISSUE THREAD

**Issue by mshick** [ronik-design/react-drive-in#19]
Would be a great feature to have. Ability to set background videos on different page elements, many per page possible.

**Comment by logicmason** [comment]
Seconded.

**Comment by mshick** [comment]
Okay, this has landed. New "multi-mode" which just means, I'm not do anything that would prevent multiple instances on the same page. See an example: http://ronik-design.github.io/react-drive-in/multi.html
