### ISSUE TITLE
Video displaying in front of elements

### ISSUE THREAD

**Issue by shanemcgraw** [ronik-design/react-drive-in#30]
I'm trying to render the <DriveIn> component along with a few others on a page, however, for the life of me I can't figure out how to display the other components in front of the video. Each time I try, the <DriveIn> component loads and it blocks the others.

For lack of a better term, is there a way to 'send video to back' (nest components inside <DriveIn> so that they appear over the video)?

**Comment by shanemcgraw** [comment]
Sigh. z-index to the rescue. Closing.

**Comment by mshick** [comment]
@shanemcgraw :)

Glad you sorted it out!
